name: Deploy

permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04-large
    timeout-minutes: 180

    env:
      NODE_OPTIONS: --max_old_space_size=32768

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      # 添加特定Rspress构建缓存
      - name: Cache Rspress build
        uses: actions/cache@v3
        with:
          path: |
            ~/.pnpm-store
            node_modules
            .rspress/cache
          key: ${{ runner.os }}-rspress-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-rspress-

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: |
          echo "Starting build..."
          pnpm run build
          echo "Build completed!"

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: doc_build