name: Deploy

permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60  # 增加超时时间

    env:
      NODE_OPTIONS: --max_old_space_size=8192  # 增加Node内存限制

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      # 添加特定Rspress构建缓存
      - name: Cache Rspress build
        uses: actions/cache@v3
        with:
          path: |
            ~/.pnpm-store
            node_modules
            .rspress/cache  # Rspress特定缓存目录
          key: ${{ runner.os }}-rspress-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-rspress-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile  # 使用固定lockfile更安全

      - name: Build
        run: |
          echo "Starting build..."
          pnpm run build --verbose  # 添加verbose获取更多日志
          echo "Build completed!"

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: doc_build  # 确保这是Rspress的正确输出目录